### ISSUE TITLE
Eddy is not working within nipype

### ISSUE THREAD

**Issue by MariaICL** [c3nl-neuraldynamics/c3nl_cluster#49]
The diffusion preprocessing pipeline (used to analyse NODDI data), which had been working until about two months ago (even in the new cluster), now produces an error when reaching the fsl Eddy part (Eddy does not even start running). Other commands from fsl (such as topup) work fine.

This is the error:
```
Executing node eddy in dir: /home/myanezl2/test_nipype_2/expdir_Saracens_NODDI_XNAT_RUGBY/CIF_S02479_RUGBY_17_v1/NODDI_XNAT_prepoc/eddy
171006-17:21:10,662 workflow INFO:
         Running: eddy_openmp --acqp=/home/myanezl2/test_nipype_2/expdir_Saracens_NODDI_XNAT_RUGBY/CIF_S02479_RUGBY_17_v1/NODDI_XNAT_prepoc/acqparams/acqparams.txt --bvals=/home/myanezl2/test_nipype_2/expdir_Saracens_NODDI_XNAT_RUGBY/CIF_S02479_RUGBY_17_v1/NODDI_XNAT_prepoc/dcm2nii_noddi/20170926_093238NODDI90dir9b0multishells018a001.bval --bvecs=/home/myanezl2/test_nipype_2/expdir_Saracens_NODDI_XNAT_RUGBY/CIF_S02479_RUGBY_17_v1/NODDI_XNAT_prepoc/dcm2nii_noddi/20170926_093238NODDI90dir9b0multishells018a001.bvec --imain=/home/myanezl2/test_nipype_2/expdir_Saracens_NODDI_XNAT_RUGBY/CIF_S02479_RUGBY_17_v1/NODDI_XNAT_prepoc/dcm2nii_noddi/20170926_093238NODDI90dir9b0multishells018a001.nii --index=/home/myanezl2/test_nipype_2/expdir_Saracens_NODDI_XNAT_RUGBY/CIF_S02479_RUGBY_17_v1/NODDI_XNAT_prepoc/index/index.txt --mask=/home/myanezl2/test_nipype_2/expdir_Saracens_NODDI_XNAT_RUGBY/CIF_S02479_RUGBY_17_v1/NODDI_XNAT_prepoc/getMask/brainmask_warped_out_flirt_maths.nii.gz --topup=/home/myanezl2/test_nipype_2/expdir_Saracens_NODDI_XNAT_RUGBY/CIF_S02479_RUGBY_17_v1/NODDI_XNAT_prepoc/TOPUP/20170926_093238NODDI90dir9b0multishells018a001_roi_merged_base --out=/home/myanezl2/test_nipype_2/expdir_Saracens_NODDI_XNAT_RUGBY/CIF_S02479_RUGBY_17_v1/NODDI_XNAT_prepoc/eddy/eddy_corrected
171006-17:21:10,726 workflow ERROR:
         [u'Node eddy failed to run on host brodmann23d.c3nl.']
171006-17:21:10,726 workflow INFO:
         Saving crash info to /home/myanezl2/workspace/c3nl/crash-20171006-172110-myanezl2-eddy-5a2693be-b682-47a9-b582-a42dfa949c10.pklz
171006-17:21:10,726 workflow INFO:
         Traceback (most recent call last):
  File "/apps/software/anaconda/4.3.1/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/apps/software/anaconda/4.3.1/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/apps/software/anaconda/4.3.1/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/apps/software/anaconda/4.3.1/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/apps/software/anaconda/4.3.1/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "/apps/software/anaconda/4.3.1/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1724, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/apps/software/anaconda/4.3.1/lib/python2.7/site-packages/nipype/interfaces/fsl/epi.py", line 590, in _run_interface
    runtime = super(Eddy, self)._run_interface(runtime)
  File "/apps/software/anaconda/4.3.1/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1750, in _run_interface
    (self.cmd.split()[0], runtime.hostname))
IOError: command 'eddy' could not be found on host brodmann23d.c3nl
Interface Eddy failed to run.
```
The command itself (third line) works in bash, or at least it is recognised and starts running (it takes a few hours to finish). The nipype error says that the command "eddy" cannot be found, which is true, this command does not exist, but the nipype wrapper is calling "eddy_openmp" and not "eddy", so I do not understand the error message or how to fix it.

Extra information:

- Currently Loaded Modules:
  1) camino/25May17   2) matlab/2016b   3) anaconda/4.3.1   4) mricron/27Dec2012   5) freesurfer/6.0.0   6) LCmodel/std   7) ANTs/4b245d5   8) fsl/5.0.9

- Example of code that immediately produces the error (both in the terminal or in pycharm): 

/home/myanezl2/workspace/c3nl/NODDI_XNAT_freesurfer_tmp.py

**Comment by MariaICL** [comment]
Further information:
I have run the same pipeline in my local mac computer, with no issues. I am using the same nipype, anaconda and fsl versions, so I suspect the issue has to do with the fsl software in the cluster having been altered in some way. Is it possible to have an out of the box fsl installation in the cluster? Maybe as another module? Or what could be done instead?
Thanks!

**Comment by MariaICL** [comment]
Update, in case someone has any similar issues at some point:

-I tried to set up an alias in my ~/.bashrc file:
```
alias eddy=eddy_openmp
```
This solved the problem in bash, but somehow not in python.

-Then Pete did a symlink in the fsl directory (/apps/software/fsl/5.0.10/bin)
```
ln -s eddy_openmp eddy
```
This solved the problem in python in the head node, still currently happening in the computer nodes, but might be a glitch and start working soon.

**Comment by MariaICL** [comment]
Also, the reason why it works in my local machine and not in the cluster is because, even though the fsl version number is the same, the installations are not identical.

**Comment by MariaICL** [comment]
Update: It is working now in the computer nodes, thanks!!
